spring.application.name=SmartEduBackend

spring.data.mongodb.uri=mongodb://localhost:27017/smartedu
spring.data.mongodb.database=smartedu

jwt.secret=3j8k2l4m9n5p7q0r1s6t8u2v3w4x5y6z7a8b9c0d1e2f

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=myprojectisuru@gmail.com
spring.mail.password=eslpgcdqzelypxgh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.root=info
logging.file.name=./../.log


spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
